name: Deploy to Github pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout action
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      # environment values
      - name: Environment ğŸˆ
        run: |
          touch .env &&
          echo NEXT_PUBLIC_GOOGLE_ANALYTICS=${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS }} >> .env &&
          echo WEBSITE_URL=${{ secrets.WEBSITE_URL }} >> .env &&

          cat .env

      - name: ğŸ˜° Clear cache
        run: rm -rf node_modules package-lock.json yarn.lock out .next && npm cache clean -f

      - name: ğŸ¤– Install
        run: yarn

      - name: ğŸ”¨ Build
        run: yarn build

      - name: ğŸ“¦ Export
        run: yarn export

      # - name: ğŸ“ Build sitemap
      #   run: yarn sitemap

      - run: touch ./out/.nojekyll

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: out # The folder the action should deploy.
          clean: true
